# Code Generated by Sidekick is for learning and experimentation purposes only.
subscription_id = "ad8f925e-d2a1-4d4a-bb51-3421875c3089"
project_name    = "miniapp"
environment     = "dev"
location        = "canadacentral"
node_count      = 1
node_vm_size    = "Standard_DS2_v2"

tags = {
  owner = "Kadhar Ali J"
  app   = "miniapp"
}
