# Code Generated by Sidekick is for learning and experimentation purposes only.
subscription_id = "00000000-0000-0000-0000-000000000000"
project_name    = "miniapp"
environment     = "dev"
location        = "canadacentral"
node_count      = 1
node_vm_size    = "Standard_DS2_v2"

tags = {
  owner = "your-name"
  app   = "miniapp"
}
