# Code Generated by Sidekick is for learning and experimentation purposes only.
variable "subscription_id" {
  description = "Azure subscription ID."
  type        = string
}

variable "project_name" {
  description = "Short project name used in resource naming."
  type        = string
  default     = "miniapp"
}

variable "environment" {
  description = "Environment name."
  type        = string
  default     = "dev"
}

variable "location" {
  description = "Azure region."
  type        = string
  default     = "canadacentral"
}

variable "kubernetes_version" {
  description = "Optional AKS version. Leave null to let Azure choose a supported default."
  type        = string
  default     = null
}

variable "node_count" {
  description = "System node pool size."
  type        = number
  default     = 1
}

variable "node_vm_size" {
  description = "VM size for AKS system node pool."
  type        = string
  default     = "Standard_DS2_v2"
}

variable "acr_sku" {
  description = "SKU for Azure Container Registry."
  type        = string
  default     = "Basic"
}

variable "vnet_address_space" {
  description = "Address space for the VNet."
  type        = list(string)
  default     = ["10.20.0.0/16"]
}

variable "aks_subnet_cidr" {
  description = "CIDR for the AKS subnet."
  type        = string
  default     = "10.20.1.0/24"
}

variable "service_cidr" {
  description = "Kubernetes service CIDR."
  type        = string
  default     = "10.30.0.0/16"
}

variable "dns_service_ip" {
  description = "Kubernetes DNS service IP."
  type        = string
  default     = "10.30.0.10"
}

variable "log_analytics_retention_days" {
  description = "Retention in days for Log Analytics."
  type        = number
  default     = 30
}

variable "tags" {
  description = "Extra tags to apply to resources."
  type        = map(string)
  default     = {}
}
