// Code Generated by Sidekick is for learning and experimentation purposes only.
const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || process.env.REACT_APP_API_BASE_URL;

export async function fetchProducts() {
  const response = await fetch(`${API_BASE_URL}/api/products`, {
    method: "GET",
    cache: "no-store",
    headers: {
      Accept: "application/json",
    },
  });

  const text = await response.text();

  if (!response.ok) {
    throw new Error(`Request failed: ${response.status} ${text}`);
  }

  let parsed;
  try {
    parsed = text ? JSON.parse(text) : null;
  } catch {
    throw new Error("API returned invalid JSON");
  }

  const rawProducts = Array.isArray(parsed)
    ? parsed
    : Array.isArray(parsed?.products)
    ? parsed.products
    : [];

  return rawProducts.map((product) => ({
    id: product.id,
    title: product.title || product.name || "Untitled product",
    name: product.name || product.title || "Untitled product",
    description: product.description || "",
    category: product.category || "Uncategorized",
    price: Number(product.price) || 0,
    image: product.image || "https://via.placeholder.com/300?text=Product",
  }));
}
