// Code Generated by Sidekick is for learning and experimentation purposes only.
import express from "express";
import cors from "cors";

const app = express();
const port = process.env.PORT || 5000;

const normalizeOrigin = (value) =>
  typeof value === "string" ? value.trim().replace(/\/$/, "") : value;

const allowedOrigins = [process.env.FRONTEND_URL]
  .filter(Boolean)
  .map(normalizeOrigin);

app.use(express.json());

app.use(
  cors({
    origin(origin, callback) {
      if (!origin) return callback(null, true);

      const normalizedOrigin = normalizeOrigin(origin);
      if (allowedOrigins.includes(normalizedOrigin)) {
        return callback(null, true);
      }

      return callback(new Error(`CORS blocked for origin: ${origin}`));
    },
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
  })
);

app.get("/api/health", (req, res) => {
  res.set("Cache-Control", "no-store");
  res.json({ status: "ok" });
});

app.get("/api/products", (req, res) => {
  res.set("Cache-Control", "no-store");
  res.json({
    products: [
      {
        id: 1,
        title: "Phone",
        name: "Phone",
        description: "Smartphone for daily use",
        category: "Electronics",
        price: 699,
        image: "https://via.placeholder.com/300?text=Phone",
      },
      {
        id: 2,
        title: "Shoes",
        name: "Shoes",
        description: "Comfortable everyday shoes",
        category: "Fashion",
        price: 89,
        image: "https://via.placeholder.com/300?text=Shoes",
      },
      {
        id: 3,
        title: "Watch",
        name: "Watch",
        description: "Classic wrist watch",
        category: "Accessories",
        price: 199,
        image: "https://via.placeholder.com/300?text=Watch",
      },
    ],
  });
});

app.listen(port, () => {
  console.log(`Server listening on port ${port}`);
});
