// Code Generated by Sidekick is for learning and experimentation purposes only.
import express from "express";
import cors from "cors";

const app = express();
const port = process.env.PORT || 5000;

app.use(express.json());

app.use(
  cors({
    origin: process.env.FRONTEND_URL,
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  })
);

app.get("/api/health", (req, res) => {
  res.json({ message: "API is running" });
});

app.get("/api/products", (req, res) => {
  res.json([
    { id: 1, name: "Phone", category: "Electronics", price: 699 },
    { id: 2, name: "Shoes", category: "Fashion", price: 89 }
  ]);
});

app.listen(port, () => {
  console.log(`Server listening on port ${port}`);
});
