// Code Generated by Sidekick is for learning and experimentation purposes only.
import express from "express";
import path from "path";
import { fileURLToPath } from "url";

const app = express();
const port = process.env.PORT || 5000;

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const staticPath = path.join(__dirname, "../public");

app.use(express.json());

// API routes first
app.get("/api/health", (req, res) => {
  res.json({ message: "E-commerce API is running" });
});

app.get("/api/products", (req, res) => {
  res.json([
    { id: 1, name: "Phone", category: "Electronics", price: 699 },
    { id: 2, name: "Shoes", category: "Fashion", price: 89 }
  ]);
});

// Serve SPA static files
app.get("/api/health", (req, res) => {
  res.json({ message: "E-commerce API is running" });
});

app.use(express.static(staticPath));

app.get("*", (req, res) => {
  res.sendFile(path.join(staticPath, "index.html"));
});
